llm:
  context_length: 1024
  device: auto
  max_tokens: 256
  model_path: ~/.ergos/models/Phi-3-mini-4k-instruct-q4.gguf
persona:
  name: Ergos
  persona_file: null
  system_prompt: You are a helpful voice assistant.
server:
  host: 0.0.0.0
  port: 8765
stt:
  device: auto
  model: tiny.en
tts:
  device: auto
  speed: 1.0
  voice: af_heart
