"""Orpheus 3B TTS synthesizer using orpheus-cpp (llama.cpp backend)."""

import logging
from collections.abc import AsyncIterator
from typing import Optional

import numpy as np

from .types import SynthesisConfig, SynthesisResult

logger = logging.getLogger(__name__)

SAMPLE_RATE = 24000


class OrpheusSynthesizer:
    """Orpheus 3B synthesizer with lazy loading and emotion tag support.

    Uses orpheus-cpp (llama.cpp backend) for expressive TTS with inline
    emotion tags: <laugh>, <chuckle>, <sigh>, <cough>, <sniffle>, <groan>,
    <yawn>, <gasp>.

    Model: isaiahbjork/orpheus-3b-0.1-ft-Q4_K_M-GGUF (~2GB VRAM at Q4_K_M)
    Output: 24kHz audio (matches Kokoro sample rate)

    The model is loaded lazily on first use via _ensure_model().
    """

    def __init__(
        self,
        n_gpu_layers: int = -1,
        lang: str = "en",
        verbose: bool = False,
    ) -> None:
        """Initialize OrpheusSynthesizer with lazy loading.

        Args:
            n_gpu_layers: Number of GPU layers to offload. -1 means all layers.
                          Set to 0 for CPU-only.
            lang: Language code for Orpheus model (default "en").
            verbose: Enable verbose llama.cpp output (default False).
        """
        self._n_gpu_layers = n_gpu_layers
        self._lang = lang
        self._verbose = verbose

        self._orpheus = None

    def _ensure_model(self):
        """Lazy load Orpheus model via orpheus-cpp."""
        if self._orpheus is not None:
            return self._orpheus

        logger.info(
            f"Loading Orpheus 3B model "
            f"(n_gpu_layers={self._n_gpu_layers}, lang={self._lang})..."
        )

        from orpheus_cpp import OrpheusCpp

        self._orpheus = OrpheusCpp(
            n_gpu_layers=self._n_gpu_layers,
            lang=self._lang,
            verbose=self._verbose,
        )

        logger.info("Orpheus 3B model loaded successfully")

        return self._orpheus

    def _build_options(self, config: SynthesisConfig) -> dict:
        """Build TTSOptions dict from SynthesisConfig."""
        return {
            "voice_id": config.orpheus_voice,
            "temperature": config.temperature,
            "top_k": config.top_k,
        }

    def synthesize(
        self,
        text: str,
        config: Optional[SynthesisConfig] = None,
    ) -> SynthesisResult:
        """Synthesize speech from text synchronously.

        Emotion tags in text are rendered as audible expression:
        <laugh>, <chuckle>, <sigh>, <cough>, <sniffle>, <groan>, <yawn>, <gasp>

        Args:
            text: Input text to synthesize (may contain emotion tags).
            config: Synthesis configuration. Uses defaults if None.

        Returns:
            SynthesisResult with float32 audio samples at 24kHz.
        """
        if config is None:
            config = SynthesisConfig()

        self._ensure_model()

        options = self._build_options(config)
        sample_rate, audio_int16 = self._orpheus.tts(text, options)

        # Convert int16 -> float32 normalized to [-1, 1]
        audio_float32 = audio_int16.astype(np.float32) / 32768.0
        duration_ms = (len(audio_float32) / SAMPLE_RATE) * 1000.0

        return SynthesisResult(
            audio_samples=audio_float32,
            sample_rate=SAMPLE_RATE,
            text=text,
            duration_ms=duration_ms,
        )

    async def synthesize_stream(
        self,
        text: str,
        config: Optional[SynthesisConfig] = None,
    ) -> AsyncIterator[tuple[np.ndarray, int]]:
        """Synthesize speech with async streaming interface.

        Streams audio chunks as they are generated by Orpheus.
        Each chunk is a (audio_float32, sample_rate) tuple.

        Args:
            text: Input text to synthesize (may contain emotion tags).
            config: Synthesis configuration. Uses defaults if None.

        Yields:
            Tuples of (audio_samples: np.ndarray[float32], sample_rate: int).
        """
        if config is None:
            config = SynthesisConfig()

        self._ensure_model()

        options = self._build_options(config)

        async for chunk_sr, audio_int16 in self._orpheus.stream_tts(text, options):
            # audio_int16 shape: (1, N) — squeeze to 1D, then convert to float32
            audio_1d = np.squeeze(audio_int16)
            audio_float32 = audio_1d.astype(np.float32) / 32768.0
            yield audio_float32, SAMPLE_RATE

    @property
    def model_loaded(self) -> bool:
        """Check if the Orpheus model is currently loaded."""
        return self._orpheus is not None

    @property
    def sample_rate(self) -> int:
        """Get the output sample rate (24000 Hz)."""
        return SAMPLE_RATE

    def close(self) -> None:
        """Release Orpheus model resources."""
        if self._orpheus is not None:
            self._orpheus = None
            logger.info("Orpheus 3B model released")
